### ISSUE TITLE
feature: move all individual helpers into NPM packages @ladjs scoped using lass

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#271]
- [x] ~_404-handler.js assigned to @OmgImAlexis~ see #308 
- [x] ~context-helpers.js~ see #313 
- [x] dynamic-view-helpers.js ~not going to do this, user should have control of this~ 
- [x] graceful.js assigned to @niftylettuce
- [x] ~i18n.js assigned to @niftylettuce~ see #311 
- [x] logger.js assigned to @OmgImAlexis 
- [x] meta.js assigned to @niftylettuce
- [x] mongoose.js assigned to @OmgImAlexis 
- [x] ~passport.js~ (see <https://github.com/ladjs/lad/issues/271#issuecomment-328366268>)
- [x] ~policies.js assigned to @niftylettuce~ see #306 
- [x] render-page.js assigned to @niftylettuce
- [x] stop-agenda.js assigned to @niftylettuce
- [x] store-ip-address.js assigned to @niftylettuce
- [x] timeout.js assigned to @niftylettuce

**Comment by niftylettuce** [comment]
please post here if you are working on one of these so I can mark it as assigned above so others don't duplicate the work.

also any packages here need to be created as a repo on @ladjs org and also published with NPM scope.

please use lass as a project starter, and for reference as to how to design and structure these helpers, defer to the logger <https://github.com/ladjs/logger>

**Comment by OmgImAlexis** [comment]
As per https://github.com/lassjs/lass/issues/10 please make sure to rename all references to yourself before pushing to Github/npm and don't use `@` in Lass' config until we fix that.

**Comment by niftylettuce** [comment]
@OmgImAlexis I've fixed https://github.com/lassjs/lass/issues/10 per <https://github.com/lassjs/is-valid-npm-name>.

To anyone helping with this issue:
* Please use `lass` v0.2.1+ as it is patched to support scoped package names (use `npm install -g lass@latest` if you need to update)
* Make sure you use `@ladjs` org scope (e.g. `@ladjs/logger`) as your helper package name

**Comment by niftylettuce** [comment]
If you need access on NPM to the `@lad` organization please ping me.

<https://www.npmjs.com/org/lad>

**Comment by niftylettuce** [comment]
- [ ] We need to integrate `@ladjs/logger`

**Comment by niftylettuce** [comment]
- [ ] We need to integrate `@ladjs/store-ip-address` (assigned to @niftylettuce)

**Comment by OmgImAlexis** [comment]
To anyone creating these make sure if you're passing `logger` as a opt that you set the default to console.

```
const reconnect = ({
  mongodb,
  mongodbOptions,
  mongooseReconnectMs,
  logger = console
}) => {
});
```

**Comment by niftylettuce** [comment]
- [ ] Need to integrate mongoose helper and publish it to npm with `npm publish --access=public`

**Comment by niftylettuce** [comment]
- [ ] We need to also take `stopAgenda` out of graceful and mongoose helpers and put it into its own package probably?

**Comment by niftylettuce** [comment]
- [ ] Need to integrate meta helper per <https://github.com/ladjs/meta> `@ladjs/meta`

**Comment by niftylettuce** [comment]
- [ ] When completely done here go through each repo and make sure all the badges and CI and code coverage are configured

**Comment by niftylettuce** [comment]
- [ ] Need to integrate timeout helper per <https://github.com/ladjs/koa-better-timeout>

**Comment by niftylettuce** [comment]
- [ ] Need to integrate render page helper per <https://github.com/ladjs/koa-views-render>

**Comment by niftylettuce** [comment]
- [x] Need to integrate `koa-isajax`

**Comment by niftylettuce** [comment]
@OmgImAlexis just fyi I'm doing `stop-agenda` right now so you don't need to.  I also am fixing usage of the existing helpers integrated and removing old ones that no longer need to be there.  If you start to focus on something just ping me in Slack first so we don't overlap.

**Comment by niftylettuce** [comment]
Just an update - we are NOT going to make passport into a helper, it's way too early to want to control authentication methods.  Should be up to user how to handle logins.  Some users might add other logins so we don't want to limit or enforce them.

**Comment by niftylettuce** [comment]
- [ ] need to integrate `stop-agenda` into Mongoose and graceful (I'm almost done with this)

**Comment by niftylettuce** [comment]
I am currently working on graceful, i18n, and policies.  I just finished stop-agenda and will be integrated that into mongoose and graceful helpers momentarily.

**Comment by niftylettuce** [comment]
- [ ] once we're done with all helpers we need to ensure LICENSE are all (c) Niftylettuce LLC

**Comment by niftylettuce** [comment]
closing this issue in favor of individual issues

see #312 for more information on this issue/related
