### ISSUE TITLE
future: alpha shiplist

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#312]
- [x] fix i18n #311
- [x] put i18n into a class @ladjs/i18n #310
- [x] convert jobs/email and jobs/locales into @ladjs/email and @ladjs/locales #309
- [x] convert _404-handler into a component #308
- [x] move dynamic helpers into 3 packages (@ladjs/state-ctx, @ladjs/state-flash, @ladjs/state-locals) #307
- [x] move policies into a class @ladjs/policies #306
- [x] write a basic test for API and web to hit all public endpoints to get 200 code w/supertest/superagent or something #305
- [x] koa-better-views integration #304 
- [x] move context-helpers into a class #313
- [x] fix env overriding
  - [x] https://github.com/keithmorris/node-dotenv-extended/pull/13
  - [x] https://github.com/keithmorris/node-dotenv-extended/issues/12
  - [x] https://github.com/motdotla/dotenv/pull/226
- [x] fix koa-response-time header not getting added to request in web.js and api.js
- [x] koa-better-error-handler (need to use `this.state.meta.title` and `this.state.meta.description`
  > koa-better-error-handler set `this.state.title` to Not Found +0ms
  > koa-better-error-handler set `this.state.desc` to Not Found +0ms
