### ISSUE TITLE
2.0.0 Release Wishlist

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#367]
# 2.0.0 Release Wishlist

## Features

- [ ] Add Docker compose (#357)
- [ ] Add `cache-pug-templates` to cache Pug files (#343)
- [ ] Port `express-redirect-loop` to Koa once (#363)
- [ ] Add `mongoose-paranoid-plugin` once <https://github.com/euqen/mongoose-paranoid-plugin/issues/6> is resolved (#347)

### Swagger

Automatic code introspection and Swagger YAML file generation (parses routes, allows inline annotations for overriding/enhancing YAML file, parses mocks/tests for parameters and request body params, parses response for object and its properties, parses available status codes based off complete code coverage, uses widdershins -> shins and swagger-ui for "try it out" code blocks, postman integration, open api v3 spec testing)

**Comment by niftylettuce** [comment]
Moved from #368:

- [ ] Drop momentjs
- [ ] `moment` and usage of `i18n.api.t` and `i18n.translate` in models, views, and email templates need to use localization of user
- [ ] Sitemap crawler
- [ ] Babel polyfill vs polyfill.io
- [ ] Two factor authentication
- [ ] Admin filtering by group, search by name/email
- [ ] User avatar upload (via lipo.io) (@niftylettuce will handle)
- [ ] Manifest PNG icon (@niftylettuce will handle)
- [ ] Figure out how to add `lint-staged`'s `xo --fix && git add` to the `template/package.json` file (right now it errors out, see https://github.com/sudo-suhas/lint-staged-multi-pkg possibly we can use lerna or something)
- [ ] Record demo video and put it on README
- [ ] Lad LTS 1.0.0 "Chap"
- [ ] Lad email verification to verify account (otherwise someone can register in advance of someone else signing up for an account, then third party signs in with Google/GitHub)
- [ ] Deprecations:
    ```sh
    0|web      | ⚠  warning   The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6 {
    0|web      |   app: {
    0|web      |     name: 'lad',
    0|web      |     version: '0.0.2',
    0|web      |     node: 'v12.10.0',
    0|web      |     hash: 'ecec4017fb14fd299e161b30b5e93c7c73f52041',
    0|web      |     environment: 'production',
    0|web      |     hostname: 'lad-demo-1',
    0|web      |     pid: 699
    0|web      |   }
    0|web      | }
    0|web      | ⚠  warning   The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6 {
```
- [ ] proxy server should remove "www" prefix from host on redirect
- [ ] server setup script needs --webroot-path #352 (?)
- [ ] Browser `setAppInfo` and `parse-logs` to parse this if it was passed
- [ ] Emails when security changes made (web/api account update or key rotation)
- [ ] Document all env vars that can be customized (e.g. `rg "process.env" node_modules`)

**Comment by niftylettuce** [comment]
- [ ] https://github.com/cabinjs/cabin/issues/133

**Comment by niftylettuce** [comment]
cc @shaunwarman 	I added above "OTP tests need added" checkbox

**Comment by niftylettuce** [comment]
- [ ] https://github.com/OptimalBits/bull/issues/1659

**Comment by niftylettuce** [comment]
- [ ] Programmatically include a `polyfill.js` file with required plugins (vs. using all plugins) via https://github.com/babel/babel-polyfills/pull/13#event-3362558265 and https://github.com/babel/babel/issues/11583

**Comment by niftylettuce** [comment]
- [ ] Upgrade to pug v3.x+ once <https://github.com/pugjs/pug/issues/3260> is resolved

**Comment by niftylettuce** [comment]
- [ ] Referrer Header Policy https://scotthelme.co.uk/a-new-security-header-referrer-policy/
- [ ] Feature Header Policy https://scotthelme.co.uk/a-new-security-header-feature-policy/

**Comment by niftylettuce** [comment]
- [ ] Report-To header (we already have `reportUri` option being used in `helmet`)

**Comment by niftylettuce** [comment]
- [ ] Implement https://github.com/koajs/qs once new major version released

**Comment by niftylettuce** [comment]
- [ ] Managed translation override concept (also investigate why Markdown not working in `mandarin.markdown()`)

**Comment by niftylettuce** [comment]
- [ ] Note that users must install gifsicle deps https://github.com/imagemin/gifsicle-bin/issues/79

**Comment by niftylettuce** [comment]
- [ ] `axe` should only use `parse-app-info` in non-development and non-testing environment (configurable)

**Comment by niftylettuce** [comment]
- [ ] prefix koa cash keys with `koa-cash:` or something

**Comment by niftylettuce** [comment]
- [ ] `X-Cached-Result: true` (or `false` value) in `koa-cash` as an option `addHeader: true` enabled by default, and version bump it

**Comment by niftylettuce** [comment]
- [ ] improve caching by content-encoding gzip on fonts+svg (not sure why they aren't)

![Screen Shot 2020-06-21 at 5 07 40 AM](https://user-images.githubusercontent.com/523141/85221902-3d5cd780-b37d-11ea-8040-346619f367b4.png)

**Comment by niftylettuce** [comment]
- [ ] add cache policy option to `koa-cash` 

![Screen Shot 2020-06-21 at 5 05 48 AM](https://user-images.githubusercontent.com/523141/85221916-4cdc2080-b37d-11ea-93c3-c85b47bd45ce.png)

**Comment by niftylettuce** [comment]
All of the above issues are now for v3.0.0 release or later.

**Comment by niftylettuce** [comment]
- [ ] Add ability to "Cancel" a pending email address change
- [ ] Investigate if reset password functionality circumvents 2FA
- [ ] Move /change-email to /my-account/change-email

**Comment by niftylettuce** [comment]
- [ ] Changing password should prompt for re-entry of password and OTP to continue
- [ ] Changing email should prompt for re-entry of password and OTP to continue

**Comment by niftylettuce** [comment]
- [ ] Configurable rate limit middleware that's specific to endpoints that send emails or insert data into database (e.g. contact form, signup, verify email, forgot password, reset password, change email, etc)
